/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cardlayout;

import java.awt.CardLayout;

/**
 *
 * @author Henrique
 */
public class CardLayoutJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CardLayoutJFrame
     */
    public CardLayoutJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        comboBoxPane = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox();
        cartoes = new javax.swing.JPanel();
        cartaoComBotoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cartaoComTexto = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        cartaoComCheckbox = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo Netbeans com CardLayout");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cartão com JButtons", "Cartão com JTextField", "Cartão com JCheckbox" }));
        cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout comboBoxPaneLayout = new javax.swing.GroupLayout(comboBoxPane);
        comboBoxPane.setLayout(comboBoxPaneLayout);
        comboBoxPaneLayout.setHorizontalGroup(
            comboBoxPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(comboBoxPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(comboBoxPaneLayout.createSequentialGroup()
                    .addGap(0, 117, Short.MAX_VALUE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 117, Short.MAX_VALUE)))
        );
        comboBoxPaneLayout.setVerticalGroup(
            comboBoxPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(comboBoxPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(comboBoxPaneLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        getContentPane().add(comboBoxPane);

        cartoes.setLayout(new java.awt.CardLayout());

        cartaoComBotoes.setName("Cartão com JButtons"); // NOI18N
        cartaoComBotoes.setLayout(new javax.swing.BoxLayout(cartaoComBotoes, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("jButton1");
        cartaoComBotoes.add(jButton1);

        jButton2.setText("jButton2");
        cartaoComBotoes.add(jButton2);

        jButton3.setText("jButton3");
        cartaoComBotoes.add(jButton3);

        cartoes.add(cartaoComBotoes, "Cartão com JButtons");

        cartaoComTexto.setName("Cartão com JTextField"); // NOI18N

        jTextField1.setText("Campo com texto de exemplo");

        javax.swing.GroupLayout cartaoComTextoLayout = new javax.swing.GroupLayout(cartaoComTexto);
        cartaoComTexto.setLayout(cartaoComTextoLayout);
        cartaoComTextoLayout.setHorizontalGroup(
            cartaoComTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(cartaoComTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cartaoComTextoLayout.createSequentialGroup()
                    .addGap(0, 111, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 110, Short.MAX_VALUE)))
        );
        cartaoComTextoLayout.setVerticalGroup(
            cartaoComTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(cartaoComTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cartaoComTextoLayout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        cartoes.add(cartaoComTexto, "Cartão com JTextField");

        cartaoComCheckbox.setName("Cartão com JCheckbox"); // NOI18N

        jCheckBox2.setText("jCheckBox2");
        cartaoComCheckbox.add(jCheckBox2);

        jCheckBox3.setText("jCheckBox3");
        cartaoComCheckbox.add(jCheckBox3);

        jCheckBox4.setText("jCheckBox4");
        cartaoComCheckbox.add(jCheckBox4);

        jCheckBox5.setText("jCheckBox5");
        cartaoComCheckbox.add(jCheckBox5);

        cartoes.add(cartaoComCheckbox, "Cartão com JCheckbox");

        getContentPane().add(cartoes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemStateChanged
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(cartoes.getLayout());
        cl.show(cartoes, (String)evt.getItem());
        
    }//GEN-LAST:event_cbItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardLayoutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardLayoutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardLayoutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardLayoutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardLayoutJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartaoComBotoes;
    private javax.swing.JPanel cartaoComCheckbox;
    private javax.swing.JPanel cartaoComTexto;
    private javax.swing.JPanel cartoes;
    private javax.swing.JComboBox cb;
    private javax.swing.JPanel comboBoxPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
